HACK: turn off stack overflow checks on flash algo
probe-rs output:
```
INFO probe_rs::flashing::flasher: Done erasing sector. Result is 0. This took 235.573858ms
INFO probe_rs::flashing::flasher: Erasing sector at address 0x10016000
WARN wait_for_completion: probe_rs::flashing::flasher: Waiting for routine call completion. timeout=33s
INFO probe_rs::flashing::flasher: Done erasing sector. Result is 0. This took 227.207591ms
INFO probe_rs::flashing::flasher: Erasing sector at address 0x10017000
WARN wait_for_completion: probe_rs::flashing::flasher: Waiting for routine call completion. timeout=33s
INFO probe_rs::flashing::flasher: Done erasing sector. Result is 0. This took 234.597496ms
INFO probe_rs::flashing::flasher: Erasing sector at address 0x10018000
WARN wait_for_completion: probe_rs::flashing::flasher: Waiting for routine call completion. timeout=33s
INFO probe_rs::flashing::flasher: Done erasing sector. Result is 0. This took 243.921127ms
INFO probe_rs::flashing::flasher: Erasing sector at address 0x10019000
WARN wait_for_completion: probe_rs::flashing::flasher: Waiting for routine call completion. timeout=33s
INFO probe_rs::flashing::flasher: Done erasing sector. Result is 0. This took 222.239064ms
INFO probe_rs::flashing::flasher: Erasing sector at address 0x1001a000
WARN wait_for_completion: probe_rs::flashing::flasher: Waiting for routine call completion. timeout=33s
INFO probe_rs::flashing::flasher: Done erasing sector. Result is 0. This took 220.052336ms
INFO probe_rs::flashing::flasher: Erasing sector at address 0x1001b000
WARN wait_for_completion: probe_rs::flashing::flasher: Waiting for routine call completion. timeout=33s
INFO probe_rs::flashing::flasher: Done erasing sector. Result is 0. This took 193.796223ms
INFO probe_rs::flashing::flasher: Erasing sector at address 0x1001c000
WARN wait_for_completion: probe_rs::flashing::flasher: Waiting for routine call completion. timeout=33s
INFO probe_rs::flashing::flasher: Done erasing sector. Result is 0. This took 206.206559ms
INFO probe_rs::flashing::flasher: Erasing sector at address 0x1001d000
WARN wait_for_completion: probe_rs::flashing::flasher: Waiting for routine call completion. timeout=33s
INFO probe_rs::flashing::flasher: Done erasing sector. Result is 0. This took 197.739183ms
INFO probe_rs::flashing::flasher: Erasing sector at address 0x1001e000
WARN wait_for_completion: probe_rs::flashing::flasher: Waiting for routine call completion. timeout=33s
WARN wait_for_completion: probe_rs::flashing::flasher: POINT 3 timeout=33s
INFO session_drop: probe_rs::session: Core status: Halted(Request)
INFO probe_rs::architecture::arm::sequences: Powering down debug port Multidrop(11002927)
INFO probe_rs::architecture::arm::sequences: Powering down debug port Multidrop(11002927)
INFO probe_rs::util::logging: Wrote log to "log-run.txt"
Error: The flashing procedure failed for '../../CoreDebug/embassy-net-rp-self-debug//target/thumbv6m-none-eabi/debug/embassy-net-rp-self-debug'.

Caused by:
  0: Failed to erase flash sector at address 0x1001e000.
  1: Stack overflow detected during Erase.
```